# Generated by Django 3.2.3 on 2021-06-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='dev_mainuddin_profile/photo/'),
        ),
    ]
